language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  - TRAVIS_NODE_VERSION="4"

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

cache:
  directories:
  - $HOME/.composer/cache
  - $HOME/node_modules

before_install:
  - composer selfupdate
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g grunt-cli

install:
  - npm install
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - npm test
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - test -e build/logs/clover.xml && wget https://scrutinizer-ci.com/ocular.phar
  - test -e build/logs/clover.xml && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
